baseURL = "https://tomodachi94.github.io/"
languageCode = "en-us"
title = "Tomodachi94's Musings"
copyright = "Copyright © 2023, Tomodachi94. All Rights Reserved unless explicitly stated."

theme = "hugo-bearblog"

staticDir = ["static"]

[outputs]
home = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'friendly'
lineNos = true
lineNumbersInTable = false
codeFences = true
